package com.sms.dto;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import com.sms.entity.Designation;
import com.sms.entity.Gender;
import com.sms.entity.Qualification;
import com.sms.enums.RecordStatus;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@Schema(
    name = "FacultyResponseDto",
    description = "Response DTO containing complete faculty information."
)
public class FacultyResponseDto {

    @Schema(
        description = "Unique faculty ID",
        example = "1"
    )
    private Long id;

    @Schema(
        description = "Associated User ID",
        example = "101"
    )
    private Long userId;

    @Schema(
        description = "Unique employee code generated by the system",
        example = "FAC0001"
    )
    private String employeeCode;

    @Schema(
        description = "Faculty first name",
        example = "Rahul"
    )
    private String firstName;

    @Schema(
        description = "Faculty last name",
        example = "Sharma"
    )
    private String lastName;

    @Schema(
        description = "Faculty mobile number",
        example = "9876543210"
    )
    private String phoneNumber;

    @Schema(
        description = "Faculty gender",
        example = "MALE"
    )
    private Gender gender;

    @Schema(
        description = "Faculty date of birth",
        example = "1990-05-15"
    )
    private LocalDate dateOfBirth;

    @Schema(
        description = "Faculty joining date",
        example = "2024-07-01"
    )
    private LocalDate joiningDate;

    @Schema(
        description = "Faculty designation",
        example = "ASSISTANT_PROFESSOR"
    )
    private Designation designation;

    @Schema(
        description = "Highest qualification of the faculty",
        example = "MTECH"
    )
    private Qualification qualification;

    @Schema(
        description = "Faculty monthly salary",
        example = "65000.00"
    )
    private BigDecimal salary;

    @Schema(
        description = "Faculty profile image URL or file path",
        example = "/uploads/faculty/rahul-sharma.jpg"
    )
    private String profileImage;

    @Schema(
        description = "Current record status",
        example = "ACTIVE"
    )
    private RecordStatus status;

    @Schema(
        description = "Department ID",
        example = "2"
    )
    private Long departmentId;

    @Schema(
        description = "Department name",
        example = "Computer Science"
    )
    private String departmentName;

    @Schema(
        description = "Address ID",
        example = "15"
    )
    private Long addressId;

    @Schema(
        description = "Village name",
        example = "Gangadahani"
    )
    private String villageName;

    @Schema(
        description = "Record creation timestamp",
        example = "2026-07-15T10:30:45"
    )
    private LocalDateTime createdAt;

    @Schema(
        description = "Record last updated timestamp",
        example = "2026-07-20T14:15:30"
    )
    private LocalDateTime updatedAt;

}