package com.sms.fee.dto;

import java.time.LocalDate;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.PastOrPresent;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Schema(
        name = "StudentFeeReceiptRequestDto",
        description = "Request DTO used for generating student fee receipt"
)
public class StudentFeeReceiptRequestDto {



    // =====================================================
    // Receipt Date
    // =====================================================


    @PastOrPresent(
            message = "Receipt date cannot be future date"
    )
    @Schema(
            description = "Receipt generation date. If not provided system will use current date",
            example = "2026-07-20"
    )
    private LocalDate receiptDate;





    // =====================================================
    // Generated By
    // =====================================================


    @Schema(
            description = "User id who generated the receipt",
            example = "1"
    )
    private Long generatedBy;





    // =====================================================
    // Remarks
    // =====================================================


    @Size(
            max = 500,
            message = "Remarks cannot exceed 500 characters"
    )
    @Schema(
            description = "Additional remarks for receipt",
            example = "First semester fee payment receipt"
    )
    private String remarks;



}