package com.sms.fee.dto;


import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import com.sms.enums.RecordStatus;
import com.sms.fee.enums.PaymentMode;
import com.sms.fee.enums.PaymentStatus;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;



@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder

@Schema(
        name = "StudentFeeReceiptResponseDto",
        description = "Response DTO containing complete student fee receipt snapshot details."
)

public class StudentFeeReceiptResponseDto {



    // =====================================================
    // Receipt Information
    // =====================================================


    @Schema(
            description = "Receipt Id",
            example = "1"
    )
    private Long id;



    @Schema(
            description = "Unique receipt number",
            example = "SMS-REC-20260721-000001"
    )
    private String receiptNumber;



    @Schema(
            description = "Receipt generation date",
            example = "2026-07-21"
    )
    private LocalDate receiptDate;



    @Schema(
            description = "Generated by user id",
            example = "1"
    )
    private Long generatedBy;



    @Schema(
            description = "Receipt remarks",
            example = "First semester fee payment receipt"
    )
    private String remarks;




    // =====================================================
    // Payment Reference
    // =====================================================


    @Schema(
            description = "Original payment id",
            example = "10"
    )
    private Long paymentId;




    // =====================================================
    // Student Snapshot
    // =====================================================


    @Schema(
            description = "Student id",
            example = "5"
    )
    private Long studentId;



    @Schema(
            description = "Student full name",
            example = "Rahul Kumar"
    )
    private String studentName;



    @Schema(
            description = "Student roll number",
            example = "CS2026001"
    )
    private String rollNumber;




    // =====================================================
    // Admission Snapshot
    // =====================================================


    @Schema(
            description = "Admission id",
            example = "8"
    )
    private Long admissionId;



    @Schema(
            description = "Admission number",
            example = "ADM-2026-001"
    )
    private String admissionNumber;



    @Schema(
            description = "Academic year",
            example = "2026-2027"
    )
    private String academicYear;




    // =====================================================
    // Course Snapshot
    // =====================================================


    @Schema(
            description = "Course id",
            example = "2"
    )
    private Long courseId;



    @Schema(
            description = "Course name",
            example = "B.Tech Computer Science"
    )
    private String courseName;




    // =====================================================
    // Department Snapshot
    // =====================================================


    @Schema(
            description = "Department id",
            example = "1"
    )
    private Long departmentId;



    @Schema(
            description = "Department name",
            example = "Computer Science"
    )
    private String departmentName;




    // =====================================================
    // Semester Snapshot
    // =====================================================


    @Schema(
            description = "Semester id",
            example = "1"
    )
    private Long semesterId;



    @Schema(
            description = "Semester name",
            example = "Semester 1"
    )
    private String semesterName;




    // =====================================================
    // Scholarship Snapshot
    // =====================================================


    @Schema(
            description = "Scholarship id",
            example = "3"
    )
    private Long scholarshipId;



    @Schema(
            description = "Scholarship amount",
            example = "20000.00"
    )
    private BigDecimal scholarshipAmount;




    // =====================================================
    // Fee Snapshot
    // =====================================================


    @Schema(
            description = "Original total fee",
            example = "80000.00"
    )
    private BigDecimal totalFee;



    @Schema(
            description = "Final payable amount after scholarship",
            example = "60000.00"
    )
    private BigDecimal finalPayableAmount;



    @Schema(
            description = "Paid amount",
            example = "30000.00"
    )
    private BigDecimal paidAmount;



    @Schema(
            description = "Remaining due amount",
            example = "30000.00"
    )
    private BigDecimal dueAmount;




    // =====================================================
    // Payment Snapshot
    // =====================================================


    @Schema(
            description = "Payment status",
            example = "PARTIAL"
    )
    private PaymentStatus paymentStatus;



    @Schema(
            description = "Payment mode",
            example = "UPI"
    )
    private PaymentMode paymentMode;



    @Schema(
            description = "Payment date",
            example = "2026-07-21"
    )
    private LocalDate paymentDate;



    @Schema(
            description = "Transaction reference",
            example = "UPI987654321"
    )
    private String transactionReference;




    // =====================================================
    // Audit
    // =====================================================


    @Schema(
            description = "Record status",
            example = "ACTIVE"
    )
    private RecordStatus status;



    @Schema(
            description = "Created date time",
            example = "2026-07-21T10:30:00"
    )
    private LocalDateTime createdAt;



    @Schema(
            description = "Updated date time",
            example = "2026-07-21T10:35:00"
    )
    private LocalDateTime updatedAt;


}